export const TRANSLATIONS = {
  en: {
    pinTitle: "Lokmanya Mess",
    pinSubtitle: "Enter PIN to Access System",
    pinError: "Invalid PIN! Please try again.",
    dashboard: "Dashboard",
    customers: "Dine In",
    dinein: "Dine In",
    tiffin: "Tiffin",
    shortterm: "Short Term Member",
    collections: "Collections",
    expenses: "Expenses",
    oldcustomers: "Old Customers",
    settings: "Settings",
    logout: "Logout",
    businessDashboard: "Business Dashboard",
    manageCustomers: "Manage Dine In Members",
    manageTiffin: "Manage Tiffin Delivery",
    manageShortTerm: "Manage Short-Term Members",
    manageCollections: "Collection Reports",
    manageExpenses: "Expenditure Tracker",
    manageOldCustomers: "Archive (Old Customers)",
    appSettings: "App Settings",
    totalCollections: "Total Collections",
    activeMembers: "Active Members",
    expiringSoon: "Expiring Soon",
    pendingDues: "Pending Dues",
    expiringExpired: "Action Required (Expired, Expiring, or Pending Dues)",
    allActive: "All subscriptions are currently active!",
    custName: "Customer Name",
    phoneNo: "Phone Number",
    plan: "Plan",
    amount: "Amount",
    status: "Status",
    paused: "Paused",
    expiryDate: "Expiry Date",
    addCustomer: "Add Customer",
    exportCsv: "Export CSV",
    searchPlaceholder: "Search customers...",
    filterAll: "All Customers",
    filterActive: "Active Only",
    filterExpired: "Expired Only",
    filterExpiring: "Expiring Soon",
    noCusts: "No customer records found.",
    planCycle: "Plan & Cycle",
    planSuffix: "Plan",
    started: "Started",
    expires: "Expires",
    fee: "Subscription Fee",
    deposited: "Deposited",
    remaining: "Remaining Amount",
    duesPending: "Dues Pending",
    fullyPaid: "Fully Paid",
    editProfile: "Edit Profile",
    deleteCust: "Delete Customer",
    addNewCust: "Add New Customer",
    editCustProfile: "Edit Customer Profile",
    fullName: "Full Name *",
    aadharCard: "Aadhar Card No.",
    billingPlan: "Billing Plan",
    monthly30: "Monthly (30 days)",
    weekly7: "Weekly (7 days)",
    daily1: "Daily (1 day)",
    custom: "Custom",
    subFeeLabel: "Subscription Fee (Rs) *",
    depositLabel: "Total Amount Deposited / Paid (Rs) *",
    joinDateLabel: "Joining Date *",
    addressLabel: "Address / Room Details",
    addressPlaceholder: "e.g. Room 104, B wing",
    ownerAddress: "Mess Address",
    cancel: "Cancel",
    saveProfile: "Save Profile",
    takePhoto: "Take Photo",
    uploadPhoto: "Upload Photo",
    removePhoto: "Remove Photo",
    capture: "Capture"
  },
  mr: {
    pinTitle: "लोकमान्य मेस",
    pinSubtitle: "सिस्टममध्ये प्रवेश करण्यासाठी पिन प्रविष्ट करा",
    pinError: "चुकीचा पिन! कृपया पुन्हा प्रयत्न करा.",
    dashboard: "डॅशबोर्ड",
    customers: "डाईन-इन ग्राहक",
    dinein: "डाईन-इन ग्राहक",
    tiffin: "टिफिन डिलिव्हरी",
    shortterm: "अल्पमुदत ग्राहक",
    collections: "जमा रक्कम",
    expenses: "खर्च व्यवस्थापन",
    oldcustomers: "जुने ग्राहक (संग्रह)",
    settings: "सेटिंग्ज",
    logout: "लॉगआउट",
    businessDashboard: "व्यवसाय डॅशबोर्ड",
    manageCustomers: "डाईन-इन ग्राहक व्यवस्थापित करा",
    manageTiffin: "टिफिन डिलिव्हरी व्यवस्थापित करा",
    manageShortTerm: "अल्पमुदत ग्राहक व्यवस्थापित करा",
    manageCollections: "जमा रक्कम इतिहास",
    manageExpenses: "खर्च ट्रॅकर",
    manageOldCustomers: "जुने ग्राहक इतिहास",
    appSettings: "ॲप सेटिंग्ज",
    totalCollections: "एकूण जमा",
    activeMembers: "सक्रिय ग्राहक",
    expiringSoon: "लवकरच संपणारे",
    pendingDues: "थकीत रक्कम",
    expiringExpired: "लक्ष देणे आवश्यक (मुदत संपलेले, लवकरच संपणारे किंवा थकीत रक्कम)",
    allActive: "सर्व ग्राहकांचे प्लॅन्स सध्या सक्रिय आहेत!",
    custName: "ग्राहकाचे नाव",
    phoneNo: "फोन नंबर",
    plan: "प्लॅन",
    amount: "रक्कम",
    status: "स्थिती",
    paused: "स्थगित",
    expiryDate: "मुदत समाप्ती तारीख",
    addCustomer: "नवीन ग्राहक जोडा",
    exportCsv: "CSV एक्सपोर्ट करा",
    searchPlaceholder: "शोध ग्राहक...",
    filterAll: "सर्व ग्राहक",
    filterActive: "फक्त सक्रिय",
    filterExpired: "फक्त मुदत संपलेले",
    filterExpiring: "लवकरच संपणारे",
    noCusts: "कोणताही ग्राहक आढळला नाही.",
    planCycle: "प्लॅन आणि सायकल",
    planSuffix: "प्लॅन",
    started: "सुरू झाले",
    expires: "संपणार",
    fee: "प्लॅन शुल्क",
    deposited: "जमा रक्कम",
    remaining: "थकीत रक्कम",
    duesPending: "बाकी आहे",
    fullyPaid: "पूर्ण भरले",
    editProfile: "प्रोफाइल बदला",
    deleteCust: "ग्राहक हटवा",
    addNewCust: "नवीन ग्राहक जोडा",
    editCustProfile: "ग्राहक प्रोफाइल बदला",
    fullName: "पूर्ण नाव *",
    aadharCard: "आधार कार्ड नंबर",
    billingPlan: "बिलिंग प्लॅन",
    monthly30: "मासिक (३० दिवस)",
    weekly7: "साप्ताहिक (७ दिवस)",
    daily1: "दैनिक (१ दिवस)",
    custom: "इतर (कस्टम)",
    subFeeLabel: "प्लॅन फी (रुपये) *",
    depositLabel: "एकूण जमा रक्कम (रुपये) *",
    joinDateLabel: "सुरू झालेली तारीख *",
    addressLabel: "पत्ता / रूम तपशील",
    addressPlaceholder: "उदा. रूम १०४, बी विंग",
    ownerAddress: "मेसचा पत्ता",
    cancel: "रद्द करा",
    saveProfile: "प्रोफाइल जतन करा",
    takePhoto: "फोटो काढा",
    uploadPhoto: "फोटो अपलोड करा",
    removePhoto: "फोटो काढा",
    capture: "फोटो घ्या"
  }
};

export const marathiDict = TRANSLATIONS.mr;

